# Generated by Django 5.2.15 on 2026-06-08 10:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente desde el nombre. Edítalo solo si sabes lo que haces.', max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='descripción')),
                ('category', models.CharField(choices=[('bocaditos', 'Bocaditos'), ('sweets', 'Dulces'), ('pizzas', 'Pizzas')], db_index=True, max_length=20, verbose_name='categoría')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('coming_soon', 'Próximamente'), ('sold_out', 'Agotado'), ('inactive', 'Inactivo')], db_index=True, default='active', max_length=20, verbose_name='estado')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Posición dentro de la categoría. Menor número = aparece antes.', verbose_name='orden')),
                ('is_featured', models.BooleanField(default=False, help_text='Si está marcado, el producto se ancla al inicio de su categoría.', verbose_name='destacado')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='imagen')),
                ('meta_description', models.CharField(blank=True, help_text='Idealmente entre 150 y 160 caracteres. Aparece en Google.', max_length=160, verbose_name='meta description (SEO)')),
                ('alt_text', models.CharField(blank=True, help_text='Descripción accesible de la foto. Importante para SEO y lectores de pantalla.', max_length=160, verbose_name='texto alternativo de la imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'status'], name='catalog_pro_categor_8873b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('province', models.CharField(max_length=60, verbose_name='provincia')),
                ('canton', models.CharField(max_length=60, verbose_name='cantón')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarca para ocultar esta ubicación sin eliminarla.', verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'supermercado',
                'verbose_name_plural': 'supermercados',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['province'], name='catalog_sup_provinc_fa9902_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej.: "Pequeña", "Mediana", "Familiar".', max_length=40, verbose_name='nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio (CRC ₡)')),
                ('is_default', models.BooleanField(default=False, help_text='La variante preseleccionada en la página del producto.', verbose_name='predeterminada')),
                ('is_available', models.BooleanField(default=True, help_text='Desmarca para indicar que esta variante está agotada sin retirar las demás.', verbose_name='disponible')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'tamaño / variante',
                'verbose_name_plural': 'tamaños / variantes',
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_variant_name_per_product')],
            },
        ),
    ]
