# Generated by Django 5.2.15 on 2026-06-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Wayka', max_length=120, verbose_name='nombre del negocio')),
                ('primary_phone', models.CharField(blank=True, help_text='Ej.: +50688887777.', max_length=20, verbose_name='teléfono principal (E.164)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('street_address', models.CharField(blank=True, help_text='Línea de calle, edificio, número.', max_length=255, verbose_name='dirección')),
                ('address_locality', models.CharField(blank=True, max_length=80, verbose_name='cantón')),
                ('address_region', models.CharField(blank=True, max_length=80, verbose_name='provincia')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='código postal')),
                ('country_code', models.CharField(default='CR', max_length=2, verbose_name='código de país (ISO 3166-1 alfa-2)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('social_instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('social_facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'ajustes del sitio',
                'verbose_name_plural': 'ajustes del sitio',
            },
        ),
        migrations.CreateModel(
            name='WeekdayHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día')),
                ('open_time', models.TimeField(blank=True, help_text='Dejar vacío si el negocio está cerrado este día.', null=True, verbose_name='abre')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='cierra')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.sitesettings', verbose_name='ajustes')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('settings', 'day'), name='unique_weekday_per_settings')],
            },
        ),
    ]
